name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        run: npm publish --provenance --access public

      - run: npx changelogithub@0.13.11
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
